### ISSUE TITLE
Crush if using editor

### ISSUE THREAD

**Issue by gema-arta** [clehner/nij#4]
```
[gem@arch_xen nij]$ nij edit local
fs.js:78
    throw new TypeError('callback must be a function');
    ^

TypeError: callback must be a function
    at makeCallback (fs.js:78:11)
    at fs.unlink (fs.js:971:14)
    at Array.forEach (native)
    at /home/gem/src/nij/nij.js:728:29
    at ChildProcess.onEditorClose (/home/gem/src/nij/nij.js:301:4)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5
```

**Comment by clehner** [comment]
Thanks for reporting. Fixed now.

**Comment by gema-arta** [comment]
```
[gem@arch_xen ~]$ nij edit local
local: Missing key
local: Missing pgp
local: Missing location
```

correctly but

```
[gem@arch_xen ~]$ nij init local
/home/gem/src/nij/nij.js:405
                throw e;
                ^

TypeError: promptSync.isEOF is not a function
    at promptSyncDefault (/home/gem/src/nij/nij.js:424:17)
    at Object.commands.init (/home/gem/src/nij/nij.js:627:11)
    at Object.<anonymous> (/home/gem/src/nij/nij.js:755:25)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
```
