### ISSUE TITLE
Crush if using init

### ISSUE THREAD

**Issue by gema-arta** [clehner/nij#5]
```
[gem@arch_xen ~]$ nij edit local
local: Missing key
local: Missing pgp
local: Missing location
```

correctly but

```
[gem@arch_xen ~]$ nij init local
/home/gem/src/nij/nij.js:405
                throw e;
                ^

TypeError: promptSync.isEOF is not a function
    at promptSyncDefault (/home/gem/src/nij/nij.js:424:17)
    at Object.commands.init (/home/gem/src/nij/nij.js:627:11)
    at Object.<anonymous> (/home/gem/src/nij/nij.js:755:25)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
```

**Comment by clehner** [comment]
Does it work now?
